### PR TITLE
closes #334 ('Key Phrases' rules were never deleted)

### LINKED ISSUE #334: Removed key phrases do not actually get removed
After key phrase removing and application relaunch, removed key phrase appears back in the list.

### PR DESCRIPTION
**Pull request by Human**

### CODE REVIEW

**Comment by Human** [comment]
To clarify, this fixes the issue in the develop branch. A separate PR is being filed for the issue in the master branch.

**Comment by Human** [comment]
@Str4tocaster Hi! Travis CI is failing due to a missing crashlytics key, but I see that your more recent PRs are building. Would you like me to merge develop into my PR branch and try again? (In case you're getting deja vu, this is a PR for the develop branch. I wasn't sure how you wanted to do branch management, so I submitted a fix in each major branch.)

**Comment by Str4tocaster** [comment]
@Human, please, do some changes in this PR:
1. Do not modify PhraseList.java. I think that UI should not know about DB.
2. Do removing from PhraseTable in PhraseManager.removePhrase
3. Do not forget about null checking for phrase object
Thanks!

**Comment by Human** [comment]
@Str4tocaster I have implemented all of your feedback. I advise adding a Nullable annotation to PhraseManager.getPhrase() as a separate issue to ensure that all getPhrase() callers are warned by Studio to do a null check. (FWIW, there are two other instances where the null check is not done: PhraseListAdapter and PhraseList.)

**Comment by Str4tocaster** [comment]
Thanks for help!

**Pull request merged**
