### PR TITLE
Support In-Band registration

### PR DESCRIPTION
**Pull request by aelmahmoudy**
This addresses #11. It is finally working !

### CODE REVIEW

**Comment by grigoryfedorov** [comment]
I will test this request after finally merge feature/chat to develop. Because it does not related with chats, ok?

**Comment by aelmahmoudy** [comment]
Sure, do you prefer that I rebase it onto 'develop' chat ?

**Comment by grigoryfedorov** [comment]
Yes, I think it would be better.

**Comment by aelmahmoudy** [comment]
Ok, replaced this with #343

**Pull request closed without merging**
