### PR TITLE
Client implementation of XEP-0280 (Message Carbons)

### PR DESCRIPTION
**Pull request by Semenchikus**
Hello, guys.

Please, look at this implementation of XEP-0280. This allows Xabber to prevent missing messages which has been sent from other devices.

### CODE REVIEW

**Comment by dbanet** [comment]
@dlc2015 I'm really interested in binaries of Xabber with the support of XEP-0280.

**Comment by andrewnenakhov** [comment]
We believe that XEP-280 is now sufficient to achieve true message sync, but we'll have a look at this. Just a bit later.

**Comment by dbanet** [comment]
Thank you. It will be really-really cool and useful.

**Comment by aelmahmoudy** [comment]
Hello,

  I've merged those changes into the develop branch, please check @aelmahmoudy/XEP-0280

**Comment by aelmahmoudy** [comment]
How do I test this feature ? What I've done is installed Xabber (built with this XEP-0280 patch) on two Android devices and set them up with the same XMPP account. I sent some text from Xabber on one device to some contact, but didn't get a carbon  copy of that text on my other device.

**Comment by dbanet** [comment]
But does the server also support carbons? If it does, and you still did not get the message, then something does not work properly.

**Comment by dbanet** [comment]
@aelmahmoudy can you please share the binaries?

**Comment by aelmahmoudy** [comment]
@dbanet how do I know if the server supports carbons ?

Here's the debug APK (based on Xabber 1.0.1): https://www.androidfilehost.com/?fid=23991606952595346

**Comment by Semenchikus** [comment]
@aelmahmoudy, you can send a Discovery Info request to the server directly. If the server supports XEP-0280, there will be `<feature var='urn:xmpp:carbons:2'/>` in the response. For direct communication with the server you can use any XMPP client that has a Jabber console. For example, Gajim has XML console (Actions->Advanced->Show XML Console) so you can send the Discovery Info request and look at response from the server. You can find more information about Discovery Info [here](http://xmpp.org/extensions/xep-0280.html) at "3. Discovering Support" paragraph.

**Comment by aelmahmoudy** [comment]
@Semenchikus thanks. Seems that none of the Jabber services I use support message carbons !
For quicker reference, the XML query is:
```xml
<iq xmlns='jabber:client' id='info1' to='example.com' type='get'>
  <query xmlns='http://jabber.org/protocol/disco#info'/>
</iq>
```

**Pull request merged**
