### PR TITLE
fixes #334 in the master branch

### LINKED ISSUE #334: Removed key phrases do not actually get removed
After key phrase removing and application relaunch, removed key phrase appears back in the list.

### PR DESCRIPTION
**Pull request by Human**
To clarify, this fixes the issue in the master branch. A separate PR was filed for the issue in the develop branch.

### CODE REVIEW

**Comment by Human** [comment]
@Str4tocaster Hi! Travis CI is failing due to a missing crashlytics key, but I see that your more recent PRs are building. Would you like me to merge master into my PR branch and try again?

**Comment by Str4tocaster** [comment]
@Human Hi! Thanks for your PR. It looks ok, but I need to do small fixes and then i can merge it.

**Comment by Human** [comment]
@Str4tocaster Woo! It's my bad luck that I managed to submit this just as you were prepping a release :)

**Comment by Str4tocaster** [comment]
@Human I answer you in https://github.com/redsolution/xabber-android/pull/805. I will close this PR in master branch. Wait for you changes in PR in develop branch for merge it.

**Pull request closed without merging**
